version: "3"

services:
   db:
      image: postgres:latest
      container_name: db 
      restart: always
      environment: 
        POSTGRES_USER: phpWebDev
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: laravel
      ports: 
        - 5432:5432
      volumes:
        - ./data:/var/lib/postgresql/data
       
        


  
  
